title: "Dajun's Website"
author: "Dajun Huang"
description: "欢迎来到我的个人网站！"

email: "djhuang_1@std.uestc.edu.cn"
#twitter_username: "twitteruser"
github_username: "dajunHuang"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username  
#googleplus_username: +username

theme: "minima"
# remote_theme: pages-themes/minimal@v0.2.0

collections:
  notes: # collection for personal blog posts
    output: true

header_pages:
  - indexs.md
  - posts-date.html
  - notes-date.html
  - about.md

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  # collections: true

home_notes_limit: 8
home_posts_limit: 7

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
